# Generated by Django 4.1.2 on 2022-10-15 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='file.file'),
        ),
    ]
