# Generated by Django 4.1.4 on 2022-12-28 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='round',
            name='collection',
            field=models.ManyToManyField(to='game.collection'),
        ),
        migrations.AddField(
            model_name='collection',
            name='item',
            field=models.ManyToManyField(blank=True, to='game.item'),
        ),
    ]
