# Generated by Django 4.1.2 on 2022-11-19 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='vote',
            name='item',
        ),
    ]
