# Generated by Django 4.1.2 on 2022-10-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='item',
        ),
        migrations.AddField(
            model_name='vote',
            name='item_collection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.itemcollection'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='itemcollection',
            unique_together={('item', 'collection')},
        ),
    ]
