# Generated by Django 4.1.2 on 2022-11-16 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.item'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
