# Generated by Django 4.1.2 on 2022-11-16 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_vote_item_alter_item_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='votes',
        ),
    ]
