# Generated by Django 4.1.2 on 2022-10-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_vote_user_alter_item_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
