# Generated by Django 4.1.2 on 2022-10-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_vote_unique_together_vote_collection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.item'),
            preserve_default=False,
        ),
    ]
