# Generated by Django 4.1.2 on 2022-11-19 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_remove_item_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={},
        ),
        migrations.AddField(
            model_name='collection',
            name='item',
            field=models.ManyToManyField(blank=True, to='game.item'),
        ),
    ]
