# Generated by Django 4.1.1 on 2022-11-19 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_collection_options_collection_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.item'),
            preserve_default=False,
        ),
    ]
