# Generated by Django 4.1.2 on 2022-10-22 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_vote_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='votes',
            field=models.IntegerField(default=1),
        ),
    ]
