# Generated by Django 4.1.4 on 2022-12-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
