# Generated by Django 4.1.2 on 2022-10-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_remove_item_collection_item_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='collection',
            field=models.ManyToManyField(blank=True, to='game.collection'),
        ),
    ]
